apiVersion: v1
entries:
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Add `controller.topologySpreadConstraints`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.452.2-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.27.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3248.v65ecb_254c298-1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.452.2
    created: "2024-06-20T13:57:18.790557+01:00"
    description: 'Jenkins - Build great things at any scale! As the leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project. '
    digest: 658df657dd1b319202551ec85200c7b149be1a3f6587c4a9a754d6c9e4887f79
    home: https://www.jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    type: application
    urls:
    - https://github.com/fersimedyoussef/helm-charts-public/jenkins-5.3.0.tgz
    version: 5.3.0
generated: "2024-06-20T13:57:18.7840845+01:00"
