apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 11.0.0
    created: "2024-06-30T17:25:14.529894947Z"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: ea71d4bbd115b7ef117e8e43c8f4c1ec628e67f2767174105c7c55f374fa71a1
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/grafana-8.2.0.tgz
    version: 8.2.0
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |-
        - "update post submit helm ci and clean up (#11221)"
        - "refactor helm ci tests part I (#11188)"
        - "Update Ingress-Nginx version controller-v1.10.1"
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.10.1
    created: "2024-06-30T17:25:14.535218908Z"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: d913d86c21e84e330e98f033fb95bd727d27ddf8b676f75960095074d290f1b1
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: Gacko
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/ingress-nginx-4.10.1.tgz
    version: 4.10.1
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Update `jenkins/inbound-agent` to version `3256.v88a_f6e922152-1`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.452.2-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.27.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3256.v88a_f6e922152-1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.452.2
    created: "2024-06-30T17:25:14.53943703Z"
    description: 'Jenkins - Build great things at any scale! As the leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project. '
    digest: dfcee9df87dcf94536ac991e4c1c9257d447b29754a31b1df9052e74930f71bd
    home: https://www.jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/jenkins-5.3.3.tgz
    version: 5.3.3
  keycloak:
  - annotations:
      category: DeveloperTools
      images: |
        - name: keycloak
          image: docker.io/bitnami/keycloak:24.0.5-debian-12-r0
        - name: keycloak-config-cli
          image: docker.io/bitnami/keycloak-config-cli:5.12.0-debian-12-r5
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 24.0.5
    created: "2024-06-30T17:25:14.549626593Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 15.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: ad3e35b5db73ada401c2b47b7e9073b27fd5d16594349daf932844c60e07a239
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/keycloak-21.4.4.tgz
    version: 21.4.4
  nexus3:
  - annotations:
      artifacthub.io/alternativeName: nexus
      artifacthub.io/changes: |
        - kind: changed
          description: "Updated the _Nexus3_ OCI image to [v3.69.0](https://github.com/sonatype/nexus-public/releases/tag/release-3.69.0-02)."
    apiVersion: v2
    appVersion: 3.69.0
    created: "2024-06-30T17:25:14.551276953Z"
    description: Helm chart for Sonatype Nexus 3 OSS.
    digest: 7a02cffc6d48a2a44a0fc0bab066c7ec09603a321d5fbfe838b8165f0689e115
    home: https://www.sonatype.com/nexus-repository-oss
    icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/nexus3/icon.png
    keywords:
    - artifacts
    - dependency
    - management
    - sonatype
    - nexus
    - repository
    maintainers:
    - email: steve.hipwell@gmail.com
      name: stevehipwell
    name: nexus3
    sources:
    - https://github.com/sonatype/docker-nexus3
    - https://hub.docker.com/r/sonatype/nexus3
    - https://github.com/stevehipwell/helm-charts/
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/nexus3-4.44.0.tgz
    version: 4.44.0
  prometheus:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus/prometheus
    apiVersion: v2
    appVersion: v2.53.0
    created: "2024-06-30T17:25:14.560583116Z"
    dependencies:
    - condition: alertmanager.enabled
      name: alertmanager
      repository: https://prometheus-community.github.io/helm-charts
      version: 1.11.*
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.20.*
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.36.*
    - condition: prometheus-pushgateway.enabled
      name: prometheus-pushgateway
      repository: https://prometheus-community.github.io/helm-charts
      version: 2.13.*
    description: Prometheus is a monitoring system and time series database.
    digest: ec20cdda210a341a05ad26e18b39ea020a81af657424302d9d57fedefcd61439
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - monitoring
    - prometheus
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: naseem@transit.app
      name: naseemkullah
    - email: rootsandtrees@posteo.de
      name: zeritti
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/prometheus-25.22.0.tgz
    version: 25.22.0
  reflector:
  - apiVersion: v2
    appVersion: 7.1.262
    created: "2024-06-30T17:25:14.561280396Z"
    description: A Helm chart to deploy Reflector
    digest: 660f048fb4eb336c256f5a7892ffc89b3cf683df7bb47b84ad461c4b5c7c1d2a
    home: https://github.com/emberstack/kubernetes-reflector
    icon: https://raw.githubusercontent.com/emberstack/CDN/master/Projects/ES.FX/es.fx.1.0.0.0.png
    keywords:
    - reflector
    - controller
    - copy
    - secrets
    - configmaps
    - cert-manager
    - certificates
    maintainers:
    - email: helm-charts@emberstack.com
      name: winromulus
    name: reflector
    sources:
    - https://github.com/emberstack/kubernetes-reflector
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/reflector-7.1.262.tgz
    version: 7.1.262
  sonarqube:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: "Update SonarQube's version to 10.6.0"
        - kind: changed
          description: "Update Chart's version to 10.6.0"
        - kind: fixed
          description: "Fix the env-var templating when sourcing from secrets"
        - kind: fixed
          description: "Fix the postgresql chart's repository link"
        - kind: changed
          description: "Add support for overriding liveness/readiness probe logic"
        - kind: changed
          description: "Use a common template for Deployment and StatefulSet"
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/images: |
        - name: sonarqube
          image: sonarqube:10.6.0-community
      artifacthub.io/links: |
        - name: support
          url: https://community.sonarsource.com/
        - name: Chart Source
          url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
    apiVersion: v2
    appVersion: 10.6.0
    created: "2024-06-30T17:25:14.571999679Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      version: 10.15.0
    - condition: nginx.enabled,ingress-nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.9.1
    description: SonarQube is a self-managed, automatic code review tool that systematically
      helps you deliver clean code. As a core element of our Sonar solution, SonarQube
      integrates into your existing workflow and detects issues in your code to help
      you perform continuous code inspections of your projects. The tool analyses
      30+ different programming languages and integrates into your CI pipeline and
      DevOps platform to ensure that your code meets high-quality standards.
    digest: 386871f22dd66f246dbfe23babeaf02ec044e4878796519c1e6b91cc627b0b8b
    home: https://www.sonarqube.org/
    icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeLogo.svg
    keywords:
    - coverage
    - security
    - code
    - quality
    kubeVersion: '>= 1.24.0-0'
    maintainers:
    - email: leo.geoffroy+helm@sonarsource.com
      name: leo-geoffroy-sonarsource
    - email: carmine.vassallo@sonarsource.com
      name: carminevassallo
    - email: jeremy.cotineau@sonarsource.com
      name: jCOTINEAU
    - email: davi.koscianski-vidal@sonarsource.com
      name: davividal
    name: sonarqube
    sources:
    - https://github.com/SonarSource/helm-chart-sonarqube
    - https://github.com/SonarSource/docker-sonarqube
    - https://github.com/SonarSource/sonarqube
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/sonarqube-10.6.0+3033.tgz
    version: 10.6.0+3033
  spinnaker:
  - apiVersion: v2
    appVersion: 1.30.1
    created: "2024-06-30T17:25:14.581481042Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.1
    - condition: minio.enabled
      name: minio
      repository: ""
      version: 8.0.9
    - condition: openldap.enabled
      name: openldap
      repository: ""
      version: 1.2.3
    description: Open source Spinnaker with v1.30.1 Gitops Support
    digest: 1528b8e457a6ef52d3996a5cc56d3f3c2b16c2cd83934fe32fbdaaaecf337f96
    home: http://spinnaker.io/
    icon: https://pbs.twimg.com/profile_images/669205226994319362/O7OjwPrh_400x400.png
    maintainers:
    - email: srinivas@opsmx.io
      name: ksrinimba
    - email: mahesh.kota@opsmx.io
      name: maheshopsmx
    - email: saiteja.katabhatina@opsmx.io
      name: saitejaopsmx
    - email: abhinay.byrisetty@hotmail.com
      name: abhinaybyrisetty
    name: spinnaker
    sources:
    - https://github.com/spinnaker
    - https://github.com/OpsMx/spinnaker-helm
    - https://github.com/viglesiasce/images
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/spinnaker-2.2.17.tgz
    version: 2.2.17
generated: "2024-06-30T17:25:14.526052466Z"
