apiVersion: v1
entries:
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Add `controller.topologySpreadConstraints`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.452.2-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.27.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3248.v65ecb_254c298-1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.452.2
    created: "2024-06-20T13:43:10.4110339+01:00"
    description: 'Jenkins - Build great things at any scale! As the leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project. '
    digest: bd660de20156d0c41f533699e7e72ab6a6886e276a2fe15bc0e9d82c7ae3a9fa
    home: https://www.jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    type: application
    urls:
    - https://github.com/fersimedyoussef/helm-charts-public/jenkins-5.3.0.tgz
    version: 5.3.0
  nexus-repository-manager:
  - apiVersion: v2
    appVersion: 3.64.0
    created: "2024-06-20T13:43:10.4120277+01:00"
    deprecated: true
    description: DEPRECATED Sonatype Nexus Repository Manager - Universal Binary repository
    digest: d65474c1665c880c10d6d3b5abc537171bdd6f54394669ab0fc8977f50e4964c
    home: https://www.sonatype.com/nexus-repository-oss
    icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
    keywords:
    - artifacts
    - dependency
    - management
    - sonatype
    - nexus
    - repository
    - quickstart
    - ci
    - repository-manager
    - nexus3
    name: nexus-repository-manager
    sources:
    - https://github.com/sonatype/nexus-public
    type: application
    urls:
    - https://github.com/fersimedyoussef/helm-charts-public/nexus-repository-manager-64.2.0.tgz
    version: 64.2.0
generated: "2024-06-20T13:43:10.4026962+01:00"
