apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 11.1.0
    created: "2024-07-17T17:25:15.03462418Z"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: f4f6f3c8a39d6bf63b8a5a47d863d35f3341d1db08ca1388544bf18350795f41
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/grafana-8.3.5.tgz
    version: 8.3.5
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |
        - 'Chores: Align security contacts & chart maintainers to actual owners. (#11465)'
        - 'Merge pull request #11277 from strongjz/chart-1.10.1 (#11415)'
        - Fix helm install on cloud provider admonition block (#11394)
        - edited helm-install tips (#11393)
        - added info for aws helm install (#11390)
        - add workflow to helm release and update ct for branch (#11378)
        - release helm chart from release branch (#11276)
        - update post submit helm ci and clean up (#11220)
        - refactor helm ci tests part I (#11178)
        - Update Ingress-Nginx version controller-v1.11.0
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.11.0
    created: "2024-07-17T17:25:15.039426622Z"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 4491c4788eeba47b77c762ba56ccee1201ea736e8222c87157bb781e02d1e170
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: puerco
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/ingress-nginx-4.11.0.tgz
    version: 4.11.0
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Update `docker.io/kiwigrid/k8s-sidecar` to version `1.27.5`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.452.3-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.27.5
        - name: inbound-agent
          image: jenkins/inbound-agent:3256.v88a_f6e922152-1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.452.3
    created: "2024-07-17T17:25:15.044402865Z"
    description: 'Jenkins - Build great things at any scale! As the leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project. '
    digest: 727b8b8c24034d6f7a8a9ba55f7f4b7ee7aabc641bf9478756fc84d9bf97df0a
    home: https://www.jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/jenkins-5.4.2.tgz
    version: 5.4.2
  keycloak:
  - annotations:
      category: DeveloperTools
      images: |
        - name: keycloak
          image: docker.io/bitnami/keycloak:24.0.5-debian-12-r3
        - name: keycloak-config-cli
          image: docker.io/bitnami/keycloak-config-cli:5.12.0-debian-12-r6
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 24.0.5
    created: "2024-07-17T17:25:15.05543783Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 15.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: 5d22841e675efc8849be349a6be0f8f43ba6a50e86cd95cdc274bdc705849c8a
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/keycloak-21.7.0.tgz
    version: 21.7.0
  nexus3:
  - annotations:
      artifacthub.io/alternativeName: nexus
      artifacthub.io/changes: |
        - kind: changed
          description: "Updated the _Nexus3_ OCI image to [v3.69.0](https://github.com/sonatype/nexus-public/releases/tag/release-3.69.0-02)."
    apiVersion: v2
    appVersion: 3.69.0
    created: "2024-07-17T17:25:15.057151151Z"
    description: Helm chart for Sonatype Nexus 3 OSS.
    digest: ff314085cc1904c9898850b5a8f219d7104664cf589e5685a5cd5a4011091bc2
    home: https://www.sonatype.com/nexus-repository-oss
    icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/nexus3/icon.png
    keywords:
    - artifacts
    - dependency
    - management
    - sonatype
    - nexus
    - repository
    maintainers:
    - email: steve.hipwell@gmail.com
      name: stevehipwell
    name: nexus3
    sources:
    - https://github.com/sonatype/docker-nexus3
    - https://hub.docker.com/r/sonatype/nexus3
    - https://github.com/stevehipwell/helm-charts/
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/nexus3-4.44.0.tgz
    version: 4.44.0
  prometheus:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus/prometheus
    apiVersion: v2
    appVersion: v2.53.1
    created: "2024-07-17T17:25:15.067200515Z"
    dependencies:
    - condition: alertmanager.enabled
      name: alertmanager
      repository: https://prometheus-community.github.io/helm-charts
      version: 1.11.*
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.21.*
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.37.*
    - condition: prometheus-pushgateway.enabled
      name: prometheus-pushgateway
      repository: https://prometheus-community.github.io/helm-charts
      version: 2.14.*
    description: Prometheus is a monitoring system and time series database.
    digest: 5f41df23cb80a0539f258c44afc6e75e3bb4edcc7dfa52bda741386cd13f41e4
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - monitoring
    - prometheus
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: naseem@transit.app
      name: naseemkullah
    - email: rootsandtrees@posteo.de
      name: zeritti
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/prometheus-25.24.1.tgz
    version: 25.24.1
  reflector:
  - apiVersion: v2
    appVersion: 7.1.288
    created: "2024-07-17T17:25:15.067904836Z"
    description: A Helm chart to deploy Reflector
    digest: 605972ec7c60d96c8b28aabc2ae38395ad148d788419c6fd7d7c6b472e156927
    home: https://github.com/emberstack/kubernetes-reflector
    icon: https://raw.githubusercontent.com/emberstack/CDN/main/projects/helm-charts/generic/emberstack_icon.png
    keywords:
    - reflector
    - controller
    - copy
    - secrets
    - configmaps
    - cert-manager
    - certificates
    maintainers:
    - email: helm-charts@emberstack.com
      name: winromulus
    name: reflector
    sources:
    - https://github.com/emberstack/kubernetes-reflector
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/reflector-7.1.288.tgz
    version: 7.1.288
  sonarqube:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: "Update Chart's version to 10.6.1"
        - kind: fixed
          description: "Fix typo in the new STS template"
        - kind: fixed
          description: "Fix regression on env valuesFrom in the new STS template"
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/images: |
        - name: sonarqube
          image: sonarqube:10.6.0-community
      artifacthub.io/links: |
        - name: support
          url: https://community.sonarsource.com/
        - name: Chart Source
          url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
    apiVersion: v2
    appVersion: 10.6.0
    created: "2024-07-17T17:25:15.079110761Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      version: 10.15.0
    - condition: nginx.enabled,ingress-nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.9.1
    description: SonarQube is a self-managed, automatic code review tool that systematically
      helps you deliver clean code. As a core element of our Sonar solution, SonarQube
      integrates into your existing workflow and detects issues in your code to help
      you perform continuous code inspections of your projects. The tool analyses
      30+ different programming languages and integrates into your CI pipeline and
      DevOps platform to ensure that your code meets high-quality standards.
    digest: 73dcabc63603fcaf8040290760038d8e0aea1a6d2f9aa5edb926dcc6f1963cfb
    home: https://www.sonarqube.org/
    icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeLogo.svg
    keywords:
    - coverage
    - security
    - code
    - quality
    kubeVersion: '>= 1.24.0-0'
    maintainers:
    - email: leo.geoffroy+helm@sonarsource.com
      name: leo-geoffroy-sonarsource
    - email: carmine.vassallo@sonarsource.com
      name: carminevassallo
    - email: jeremy.cotineau@sonarsource.com
      name: jCOTINEAU
    - email: davi.koscianski-vidal@sonarsource.com
      name: davividal
    name: sonarqube
    sources:
    - https://github.com/SonarSource/helm-chart-sonarqube
    - https://github.com/SonarSource/docker-sonarqube
    - https://github.com/SonarSource/sonarqube
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/sonarqube-10.6.1+3163.tgz
    version: 10.6.1+3163
  spinnaker:
  - apiVersion: v2
    appVersion: 1.30.1
    created: "2024-07-17T17:25:15.089141125Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.1
    - condition: minio.enabled
      name: minio
      repository: ""
      version: 8.0.9
    - condition: openldap.enabled
      name: openldap
      repository: ""
      version: 1.2.3
    description: Open source Spinnaker with v1.30.1 Gitops Support
    digest: 4d0839beebaaf602d132af092d61f70014c45c920eadc7418767df3eb01f46d9
    home: http://spinnaker.io/
    icon: https://pbs.twimg.com/profile_images/669205226994319362/O7OjwPrh_400x400.png
    maintainers:
    - email: srinivas@opsmx.io
      name: ksrinimba
    - email: mahesh.kota@opsmx.io
      name: maheshopsmx
    - email: saiteja.katabhatina@opsmx.io
      name: saitejaopsmx
    - email: abhinay.byrisetty@hotmail.com
      name: abhinaybyrisetty
    name: spinnaker
    sources:
    - https://github.com/spinnaker
    - https://github.com/OpsMx/spinnaker-helm
    - https://github.com/viglesiasce/images
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/spinnaker-2.2.18.tgz
    version: 2.2.18
generated: "2024-07-17T17:25:15.030060178Z"
