apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 11.0.0
    created: "2024-06-24T12:03:45.2631707+01:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: fe73770da39c0d6f2f59bf8f18dcdd632ee16cd5ec741e40bd12cb1241e89e38
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/grafana-8.0.2.tgz
    version: 8.0.2
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Fix Tiltfile deprecated value reference
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.452.2-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.27.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3248.v65ecb_254c298-1
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.452.2
    created: "2024-06-24T12:03:45.2670948+01:00"
    description: 'Jenkins - Build great things at any scale! As the leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project. '
    digest: e10cb637b9ba3a39407fa769edc8910a0ad801588286f86c9d1868fa70eb5a02
    home: https://www.jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/jenkins-5.3.1.tgz
    version: 5.3.1
  nexus3:
  - annotations:
      artifacthub.io/alternativeName: nexus
      artifacthub.io/changes: |
        - kind: changed
          description: "Updated the _Nexus3_ OCI image to [v3.69.0](https://github.com/sonatype/nexus-public/releases/tag/release-3.69.0-02)."
    apiVersion: v2
    appVersion: 3.69.0
    created: "2024-06-24T12:03:45.2709144+01:00"
    description: Helm chart for Sonatype Nexus 3 OSS.
    digest: 944e524542661bed447d0f9b323c123ec0ea962fc2be42c08c36602e73b975fe
    home: https://www.sonatype.com/nexus-repository-oss
    icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/nexus3/icon.png
    keywords:
    - artifacts
    - dependency
    - management
    - sonatype
    - nexus
    - repository
    maintainers:
    - email: steve.hipwell@gmail.com
      name: stevehipwell
    name: nexus3
    sources:
    - https://github.com/sonatype/docker-nexus3
    - https://hub.docker.com/r/sonatype/nexus3
    - https://github.com/stevehipwell/helm-charts/
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/nexus3-4.44.0.tgz
    version: 4.44.0
  reflector:
  - apiVersion: v2
    appVersion: 7.1.262
    created: "2024-06-24T12:03:45.2715497+01:00"
    description: A Helm chart to deploy Reflector
    digest: d5a6808b8d225eb12d47f20ce0d1839214a7d6f664a31b47f20a2f292dc7131a
    home: https://github.com/emberstack/kubernetes-reflector
    icon: https://raw.githubusercontent.com/emberstack/CDN/master/Projects/ES.FX/es.fx.1.0.0.0.png
    keywords:
    - reflector
    - controller
    - copy
    - secrets
    - configmaps
    - cert-manager
    - certificates
    maintainers:
    - email: helm-charts@emberstack.com
      name: winromulus
    name: reflector
    sources:
    - https://github.com/emberstack/kubernetes-reflector
    type: application
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/reflector-7.1.262.tgz
    version: 7.1.262
  wordpress:
  - annotations:
      category: CMS
      images: |
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.7-debian-12-r9
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r22
        - name: wordpress
          image: docker.io/bitnami/wordpress:6.5.4-debian-12-r6
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 6.5.4
    created: "2024-06-24T12:03:45.2802087+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 7.x.x
    - condition: mariadb.enabled
      name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: WordPress is the world's most popular blogging and content management
      platform. Powerful yet simple, everyone from students to global corporations
      use it to build beautiful, functional websites.
    digest: 1b9bf79201a98d31dc1bc409846d086fcf25989927f378bf9c308737d339a0e1
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
    keywords:
    - application
    - blog
    - cms
    - http
    - php
    - web
    - wordpress
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: wordpress
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/wordpress
    urls:
    - https://fersimedyoussef.github.io/helm-charts-public/charts/wordpress-22.4.14.tgz
    version: 22.4.14
generated: "2024-06-24T12:03:45.2613667+01:00"
